function []=izbornik() 
disp('-----IZBORNIK------')
disp('  ')
disp('Unesite: ')
disp('1 - za crtanje grafa')
disp('2 - za jednostavne operacije - jednostavni kalkulator')
disp('3 - za doradu grafa(izgled)')
disp('0 - za izlazak')